version: '2'
services: 
  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.0
    depends_on: 
      - elasticsearch

    volumes: 
      - ./logstash/.volumes/config:/usr/share/logstash/config/
      - ./logstash/.volumes/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/.volumes/queue:/usr/share/logstash/data/queue

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports: 
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/.volumes/data:/usr/share/elasticsearch/data
      - ./elasticsearch/.volumes/config/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    depends_on: 
      - elasticsearch
    ports: 
      - 5601:5601
    #volumes: 
   #   - ./kibana/.volumes/config:/usr/share/kibana/config/
